name: DevSecOps CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # ============================
  # 1. Static Application Security Testing (SAST)
  # ============================
  sast:
    name: Static Application Security Testing (Semgrep)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep SAST scan
        run: semgrep --config auto . || true

  # ============================
  # 2. Build & Deploy DVWA
  # ============================
  build-and-deploy:
    name: Build & Deploy DVWA
    runs-on: ubuntu-latest
    needs: sast

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create Docker network
        run: docker network create dvwa-net

      - name: Start MySQL container
        run: |
          docker run -d \
            --name mysql \
            --network dvwa-net \
            -e MYSQL_ROOT_PASSWORD=root \
            -e MYSQL_DATABASE=dvwa \
            mysql:5.7

      - name: Wait for MySQL to initialize
        run: sleep 60

      - name: Build DVWA Docker image
        run: docker build -t dvwa .

      - name: Run DVWA container
        run: |
          docker run -d -p 8080:80 \
            --name dvwa \
            --network dvwa-net \
            -e MYSQL_PASS=root \
            dvwa

      - name: Wait for DVWA to start
        run: sleep 30

      - name: Verify DVWA is running
        run: curl -I http://localhost:8080 || true

  # ============================
  # 3. Dynamic Application Security Testing (DAST)
  # ============================
  dast:
    name: Dynamic Security Testing (OWASP ZAP)
    runs-on: ubuntu-latest
    needs: build-and-deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Docker network
        run: docker network create dvwa-net

      - name: Start MySQL container
        run: |
          docker run -d \
            --name mysql \
            --network dvwa-net \
            -e MYSQL_ROOT_PASSWORD=root \
            -e MYSQL_DATABASE=dvwa \
            mysql:5.7

      - name: Wait for MySQL
        run: sleep 60

      - name: Start DVWA container
        run: |
          docker run -d -p 8080:80 \
            --name dvwa \
            --network dvwa-net \
            -e MYSQL_PASS=root \
            vulnerables/web-dvwa

      - name: Wait for DVWA
        run: sleep 30

      - name: Run OWASP ZAP Baseline Scan
        run: |
          mkdir -p reports
          docker run --network host \
            -v $(pwd)/reports:/zap/wrk/:rw \
            owasp/zap2docker-stable zap-baseline.py \
            -t http://localhost:8080 \
            -r zap_report.html -l MEDIUM

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: reports/zap_report.html
